sudo: required
services:
  - docker

before_install:
  - docker build -t pslavov/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pslavov/react-test npm test

after_success:
  - docker build -t pslavov/multi-client ./client
  - docker build -t pslavov/multi-nginx ./nginx
  - docker build -t pslavov/multi-server ./server
  - docker build -t pslavov/multi-worker ./worker
  # Push to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stin
  - docker push pslavov/multi-client
  - docker push pslavov/multi-nginx
  - docker push pslavov/multi-server
  - docker push pslavov/multi-worker