sudo: required
services:
  - docker

before_install:
  - docker build -t pslavov/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pslavov/react-test npm test

after_success:
  - docker build -t pslavov/multi-client ./client
  - docker build -t pslavov/multi-nginx ./nginx
  - docker build -t pslavov/multi-server ./server
  - docker build -t pslavov/multi-worker ./worker
  # Push to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push pslavov/multi-client
  - docker push pslavov/multi-nginx
  - docker push pslavov/multi-server
  - docker push pslavov/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-1-275165835456
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY